/**
 * Wire protocol between the MCP server's HTTP bridge and the Roblox Studio plugin.
 *
 * Transport model
 * ---------------
 * Roblox Studio plugins can only make *outbound* HTTP requests, so the plugin
 * long-polls the local bridge for commands and posts results back:
 *
 *   Plugin -> POST /plugin/hello                  (handshake / reconnect announcement)
 *   Plugin -> GET  /plugin/poll?session=<id>      (held up to LONG_POLL_HOLD_MS, returns a command or 204)
 *   Plugin -> POST /plugin/result?session=<id>    (result envelope for a previously delivered command)
 *   Any    -> GET  /health                        (unauthenticated liveness probe, no data exposure)
 *
 * All /plugin/* endpoints require `Authorization: Bearer <token>`.
 * The bridge binds to 127.0.0.1 only.
 *
 * Multi-peer sessions (protocol v2)
 * ---------------------------------
 * Every Studio DataModel running the plugin connects as its own *peer*:
 *   - "edit"   : the edit-mode Studio session (also hosts Run-mode simulations)
 *   - "server" : the server DataModel of a play-solo / multiplayer playtest
 *   - "client" : a client DataModel of a playtest (one peer per simulated player)
 * Each peer announces a unique `sessionId` in its hello and carries it as the
 * `session` query parameter on every poll/result. The bridge keeps an
 * independent command queue per session so the MCP server can route commands
 * (e.g. runtime Luau eval, log reads) to a specific live peer.
 */

/** Version of this wire protocol. Bumped on breaking changes. */
export const PROTOCOL_VERSION = 2;

/** Default TCP port for the local HTTP bridge. */
export const DEFAULT_BRIDGE_PORT = 3667;

/** Default TCP port for the optional Streamable HTTP MCP transport. */
export const DEFAULT_MCP_HTTP_PORT = 3668;

/** How long the bridge holds an open /plugin/poll request before replying 204. */
export const LONG_POLL_HOLD_MS = 15_000;

/** Plugin is considered disconnected when no poll arrives within this window. */
export const PLUGIN_TIMEOUT_MS = 45_000;

/** Sessions unseen for this long are pruned from the registry. */
export const SESSION_PRUNE_MS = 10 * 60_000;

/** Default per-command timeout (server side). */
export const DEFAULT_COMMAND_TIMEOUT_MS = 30_000;

/** Upper bound for user-configurable command timeouts (e.g. run_luau). */
export const MAX_COMMAND_TIMEOUT_MS = 180_000;

export const ENDPOINTS = {
  health: "/health",
  hello: "/plugin/hello",
  poll: "/plugin/poll",
  result: "/plugin/result",
} as const;

/** Where a plugin peer runs. */
export type PeerContext = "edit" | "server" | "client";

export const PEER_CONTEXTS: readonly PeerContext[] = ["edit", "server", "client"];

/** A single command dispatched from the MCP server to the Studio plugin. */
export interface BridgeCommand {
  /** Unique command id (UUID v4). */
  id: string;
  /** Command name, e.g. "CreateInstance". Must be a known CommandName. */
  name: string;
  /** JSON-serializable payload; shape depends on the command. */
  payload: Record<string, unknown>;
  /** Milliseconds the plugin should allow the command to run before aborting. */
  timeoutMs: number;
}

/** Result envelope posted back by the plugin for a delivered command. */
export interface BridgeResult {
  /** Id of the command this result answers. */
  id: string;
  /** True when the command executed successfully. */
  ok: boolean;
  /** JSON-serializable result data (present when ok). */
  result?: unknown;
  /** Error details (present when not ok). */
  error?: BridgeError;
}

export interface BridgeError {
  message: string;
  /** Optional Luau stack trace. */
  stack?: string;
  /** Machine-readable error code. */
  code?: string;
}

/** Handshake body sent by the plugin on connect/reconnect. */
export interface PluginHello {
  pluginVersion: string;
  protocolVersion: number;
  /** Unique id for this DataModel session (GUID generated by the plugin). */
  sessionId: string;
  /** Which kind of DataModel this peer is. */
  context: PeerContext;
  placeName: string;
  placeId: number;
  gameId: number;
  /** Local player name (client peers only). */
  userName?: string;
  /** Local player user id (client peers only). */
  userId?: number;
  studioLocale?: string;
}

/** Handshake response from the bridge. */
export interface ServerHello {
  serverVersion: string;
  protocolVersion: number;
  ok: boolean;
  message?: string;
}

/** Public view of a connected peer, as reported by get_connected_peers. */
export interface PeerInfo {
  sessionId: string;
  context: PeerContext;
  connected: boolean;
  lastSeenAt: number;
  placeName: string;
  placeId: number;
  pluginVersion: string;
  userName?: string;
  userId?: number;
}

/** Connection status the bridge tracks about the edit-mode plugin. */
export interface PluginConnectionState {
  connected: boolean;
  lastSeenAt: number | null;
  hello: PluginHello | null;
}
